In [36]:
# From: 
# http://pytorch.apachecn.org/cn/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
import torch

In [2]:
from __future__ import print_function
import torch

In [6]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00 -2.5244e-29  1.9818e+22
-2.0005e+00  1.1210e-44  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



In [8]:
x = torch.rand(5, 3)
print(x)


 0.6997  0.3053  0.5944
 0.0115  0.2650  0.7967
 0.0986  0.9419  0.2127
 0.6218  0.3291  0.8905
 0.7195  0.7088  0.4839
[torch.FloatTensor of size 5x3]



In [9]:
print(x.size())

torch.Size([5, 3])


In [14]:
# addition: option 1

In [10]:
y = torch.rand(5, 3)
print(x + y)


 1.4773  0.4310  1.2570
 0.2228  0.3642  0.9905
 0.1450  1.3330  0.8474
 1.1458  0.8448  1.3156
 1.0601  1.5471  0.7060
[torch.FloatTensor of size 5x3]



In [15]:
# addition: option 2

In [11]:
print(torch.add(x, y))


 1.4773  0.4310  1.2570
 0.2228  0.3642  0.9905
 0.1450  1.3330  0.8474
 1.1458  0.8448  1.3156
 1.0601  1.5471  0.7060
[torch.FloatTensor of size 5x3]



In [16]:
# addition, give 'out' parameter

In [12]:
result = torch.Tensor(5, 3)
torch.add(x, y, out = result)
print(result)


 1.4773  0.4310  1.2570
 0.2228  0.3642  0.9905
 0.1450  1.3330  0.8474
 1.1458  0.8448  1.3156
 1.0601  1.5471  0.7060
[torch.FloatTensor of size 5x3]



In [17]:
## addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)


 1.4773  0.4310  1.2570
 0.2228  0.3642  0.9905
 0.1450  1.3330  0.8474
 1.1458  0.8448  1.3156
 1.0601  1.5471  0.7060
[torch.FloatTensor of size 5x3]



In [19]:
# selection like 'numpy' way

In [20]:
print(x[:, 1])


 0.3053
 0.2650
 0.9419
 0.3291
 0.7088
[torch.FloatTensor of size 5]



In [23]:
# change the size of tensor, like 'reshape'

In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
# change torch tensor to numpy array (using '.numpy()')

In [24]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


In [31]:
# change numpy array to torch tensor (using 'torch.from_numpy(...)')

In [29]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [35]:
# check if cuda is available
# is yes, then use 'x = x.cuda()' to go with cuda way

In [32]:
torch.cuda.is_available()

False

In [33]:
# if torch.cuda.is_available():
#     x = x.cuda()
#     y = y.cuda()
#     x + y